### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by oscarjose9423** [jonathan-roberts1/GPT4GEO#1]
Hello is there any chance the code of the project can be shared?

**Comment by jonathan-roberts1** [comment]
Hi @oscarjose9423,
Apologies for the delay. The code is not currently ready to be released, however in the meantime, if there is a particular experiment/plot that you would like the code for I can have a look into adding it to the repo sooner.

**Comment by oscarjose9423** [comment]
I have been doing research on route interpretation for supply chain or high load transportation. Ideally route can be interpreted/parsed into intersections from a text. Ideally it should acknowledge that this point/intersection exists in an geographical location/city is important.

**Comment by jonathan-roberts1** [comment]
That sounds like a really interesting project! While it covers similar topics to GPT4GEO, our code is more directed toward visualisation so won't be useful for that - apologies.
